version: "3.8"
services:
  app:
    image: fastapi_app:latest
    ports:
      - "5000:5000"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
