version: "3.8"

services:
  app:
    image: ec2-18-206-163-210.compute-1.amazonaws.com:8083/docker-hosted/fastapi_app:latest
    container_name: fastapi_app
    ports:
      - "5000:5000"
    networks:
      - app-net
    depends_on:
      - nexus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-net
    depends_on:
      - prometheus

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  nexus-data:
  grafana-data:
