version: "3.8"

services:
  fastapi-app:
    image: your-nexus-domain:8083/fastapi_app:latest
    container_name: fastapi_app
    ports:
      - "5000:5000"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-net

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
